version: '3'
services:
  back:
    build: .
    image: uploader-back:latest
    container_name: uploader-back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/opt/back

    ports:
      - 8000:8000
