# Generated by Django 4.1.5 on 2023-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='challenge',
            new_name='comprobante',
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
